export {default as RolesAndApprovalsHero} from "./RolesAndApprovalsHero"
export {default as AccessPrinciplesSection} from "./AccessPrinciplesSection"
export {default as BuildingBlocksSection} from "./BuildingBlocksSection"
export {default as ResponsibilitiesSection} from "./ResponsibilitiesSection"
export {default as ApprovalLifecycleSection} from "./ApprovalLifecycleSection"
export {default as MeaningfulReviewSection} from "./MeaningfulReviewSection"
export {default as DelegationSection} from "./DelegationSection"
export {default as AccessLifecycleSection} from"./AccessLifecycleSection"
export {default as ServiceIdentitiesSection} from "./ServiceIdentitiesSection"
export {default as AuditAndEvidenceSection} from "./AuditAndEvidenceSection"
export {default as FAQSection} from "./FAQSection"
export {default as NextStepSection} from "./NextStepSection"